"""SVG post-processing.

The tracer emits a bare list of filled paths. Everything that turns that
into a usable, editable document happens here: a proper coordinate system,
physical output size, draw styles, colour grouping, seam removal and
watermarking.
"""

from __future__ import annotations

import math
import re
from collections import OrderedDict

from lxml import etree
from PIL import Image

from app.core.errors import VectorizationFailed
from app.schemas.params import VectorizeParams
from app.utils import units

SVG_NS = "http://www.w3.org/2000/svg"
NSMAP = {None: SVG_NS}

_NUMBER_RE = re.compile(r"-?\d+\.?\d*")

_PROLOGUE = (
    b'<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
    b"<!-- Generated by Python Vector API -->\n"
)


def _q(tag: str) -> str:
    return f"{{{SVG_NS}}}{tag}"


def _fmt(value: float) -> str:
    """Compact number formatting: 300.0 -> '300', 12.3456 -> '12.346'."""
    rounded = round(value, 3)
    if rounded == int(rounded):
        return str(int(rounded))
    return f"{rounded:g}"


def parse(svg_text: str) -> etree._Element:
    parser = etree.XMLParser(remove_blank_text=False, resolve_entities=False, huge_tree=False)
    try:
        return etree.fromstring(svg_text.encode("utf-8"), parser=parser)
    except etree.XMLSyntaxError as exc:  # pragma: no cover - tracer emits valid XML
        raise VectorizationFailed(f"The tracer produced invalid SVG: {exc}") from exc


def _paths(root: etree._Element) -> list[etree._Element]:
    return list(root.iter(_q("path")))


def _apply_draw_style(paths: list[etree._Element], params: VectorizeParams) -> None:
    """Re-express each shape as fill, outline, or bare edge."""
    style = params.output_draw_style
    if style == "fill_shapes":
        return

    width = _fmt(params.output_stroke_width)
    for path in paths:
        fill = path.get("fill", "#000000")
        path.set("fill", "none")
        path.set("stroke", "#000000" if style == "stroke_edges" else fill)
        path.set("stroke-width", width)
        path.set("stroke-linejoin", "round")
        path.set("stroke-linecap", "round")


def _apply_gap_filler(paths: list[etree._Element], params: VectorizeParams) -> None:
    """Hide the hairline seams renderers leave between abutting shapes.

    Adjacent traced shapes share an edge exactly. Anti-aliasing each of them
    independently leaves a faint light line along that shared edge, so we
    stroke every shape with its own fill colour to overlap the seam.
    """
    if not params.output_gap_filler_enabled:
        return
    if params.output_draw_style != "fill_shapes":
        return  # stroked output has no seams to hide

    width = _fmt(params.output_gap_filler_stroke_width)
    for path in paths:
        fill = path.get("fill")
        if not fill or fill == "none":
            continue
        path.set("stroke", fill)
        path.set("stroke-width", width)
        path.set("stroke-linejoin", "round")


def _rgb(value: str) -> tuple[int, int, int] | None:
    value = value.strip()
    if not value.startswith("#") or len(value) not in (4, 7):
        return None
    if len(value) == 4:
        value = "#" + "".join(ch * 2 for ch in value[1:])
    try:
        return tuple(int(value[i : i + 2], 16) for i in (1, 3, 5))  # type: ignore[return-value]
    except ValueError:
        return None


def _filled_area(path: etree._Element) -> float:
    """Approximate enclosed area, used to rank colours by prominence.

    Shoelace over the path's control points. It is only an approximation for
    curves, but the important property is that it measures what a shape
    *covers* -- a bounding box does not, and a thin ring's box is as big as
    the shape it surrounds, which would rank a transition band above the fill
    it borders and merge colours in exactly the wrong direction.
    """
    numbers = [float(n) for n in _NUMBER_RE.findall(path.get("d") or "")]
    xs, ys = numbers[0::2], numbers[1::2]
    count = min(len(xs), len(ys))
    if count < 3:
        return 0.0
    total = 0.0
    for i in range(count):
        j = (i + 1) % count
        total += xs[i] * ys[j] - xs[j] * ys[i]
    return abs(total) / 2.0


def _resolve_blend(
    colour: tuple[int, int, int], targets: list[tuple[str, tuple[int, int, int]]]
) -> str:
    """Decide which palette colour a traced fill really belongs to.

    The tracer averages the pixels inside each cluster, so a cluster straddling
    a boundary comes back as a blend of the two colours either side. Snapping
    such a blend to the *nearest* palette entry is wrong, and wrong in a way
    that is very visible: the midpoint of a dark charcoal and a cream sits
    close to a sage green, so every letter grew a green outline that exists
    nowhere in the artwork.

    Instead, find the pair of palette colours whose mixture best explains the
    blend, and award it to whichever of the two dominates. A dark/cream blend
    resolves to dark or cream -- never to some third colour that merely
    happens to sit nearby in RGB space.
    """
    best_error = float("inf")
    best_name = targets[0][0]
    for i, (name_a, a) in enumerate(targets):
        for name_b, b in targets[i:]:
            delta = tuple(bc - ac for ac, bc in zip(a, b))
            length = sum(d * d for d in delta)
            if length == 0:
                weight = 0.0
            else:
                # Project the blend onto the a->b line, clamped to the segment.
                weight = sum(
                    (c - ac) * d for c, ac, d in zip(colour, a, delta)
                ) / length
                weight = max(0.0, min(1.0, weight))
            mixed = tuple(ac + weight * d for ac, d in zip(a, delta))
            error = sum((c - m) ** 2 for c, m in zip(colour, mixed))
            if error < best_error:
                best_error = error
                best_name = name_b if weight > 0.5 else name_a
    return best_name


def _snap_to_palette(paths: list[etree._Element], palette: list[str]) -> int:
    """Force every fill onto the requested palette.

    The bitmap handed to the tracer already contains exactly these colours,
    but the tracer averages within clusters, so ask for six colours and two
    hundred come out. The extras show up in an editor as ghost layers beside
    the real shapes, so they have to be resolved back to the palette.
    """
    targets = [(colour, _rgb(colour)) for colour in palette]
    targets = [(colour, rgb) for colour, rgb in targets if rgb is not None]
    if not targets:
        return 0

    snapped = 0
    cache: dict[str, str] = {}
    for path in paths:
        fill = path.get("fill")
        if not fill or fill == "none":
            continue
        if fill not in cache:
            source = _rgb(fill)
            if source is None:
                continue
            cache[fill] = _resolve_blend(source, targets)
        nearest = cache[fill]
        if nearest != fill:
            snapped += 1
        path.set("fill", nearest)
        if path.get("stroke") and path.get("stroke") != "none":
            path.set("stroke", nearest)  # gap filler tracks the fill
    return snapped


def _merge_similar_colors(paths: list[etree._Element], threshold: float) -> int:
    """Snap near-duplicate fills onto the dominant colour they sit beside.

    Anti-aliasing between two flat regions leaves a transition band, and the
    tracer emits it as its own shapes -- pale lumps sitting between a dark
    stroke and its fill. Worse, it often splits that band into fills a single
    RGB unit apart (#4d3e48 next to #4d3f48). No tracer setting merges those,
    because to the tracer they really are different colours.

    So collapse them afterwards: rank fills by how much area they cover, then
    remap each minor colour onto the nearest more-prominent one within
    *threshold* RGB distance.
    """
    if threshold <= 0:
        return 0

    area_by_color: dict[str, float] = {}
    for path in paths:
        fill = path.get("fill")
        if fill and fill != "none":
            area_by_color[fill] = area_by_color.get(fill, 0.0) + _filled_area(path)

    # Most prominent first, so minor colours dissolve into major ones and
    # never the other way round.
    ranked = sorted(area_by_color, key=lambda c: area_by_color[c], reverse=True)
    remap: dict[str, str] = {}
    for index, color in enumerate(ranked):
        source = _rgb(color)
        if source is None:
            continue
        best, best_distance = None, threshold
        for major in ranked[:index]:
            target = _rgb(remap.get(major, major))
            if target is None:
                continue
            distance = sum((a - b) ** 2 for a, b in zip(source, target)) ** 0.5
            if distance <= best_distance:
                best, best_distance = remap.get(major, major), distance
        if best is not None:
            remap[color] = best

    if not remap:
        return 0
    for path in paths:
        fill = path.get("fill")
        if fill in remap:
            path.set("fill", remap[fill])
            if path.get("stroke") == fill:  # gap filler tracks the fill
                path.set("stroke", remap[fill])
    return len(remap)


_COMMAND_RE = re.compile(r"([MLCQZmlcqz])([^MLCQZmlcqz]*)")

# Coordinate pairs consumed by each absolute path command.
_PAIRS_PER_COMMAND = {"M": 1, "L": 1, "C": 3, "Q": 2, "Z": 0}


def _shift_path_data(d: str, dx: float, dy: float) -> str | None:
    """Bake a translate into absolute path data. None if it is not safe to.

    The tracer emits a per-shape ``transform="translate(x,y)"``. Combining
    shapes into one element means their coordinates have to live in the same
    space, so the offset is folded into the numbers here.
    """
    out: list[str] = []
    for command, body in _COMMAND_RE.findall(d):
        if command not in _PAIRS_PER_COMMAND:
            return None  # relative command: leave this path alone
        if command == "Z":
            out.append("Z")
            continue
        numbers = [float(n) for n in _NUMBER_RE.findall(body)]
        if len(numbers) % 2:
            return None
        shifted = []
        for i in range(0, len(numbers), 2):
            shifted.append(_fmt(numbers[i] + dx))
            shifted.append(_fmt(numbers[i + 1] + dy))
        out.append(command + " ".join(shifted))
    return "".join(out)


_TRANSLATE_RE = re.compile(
    r"translate\(\s*(-?\d+\.?\d*)[ ,]+(-?\d+\.?\d*)\s*\)"
)


def _path_bounds(path: etree._Element) -> tuple[float, float, float, float] | None:
    """Bounding box in document space, with the shape's translate applied."""
    numbers = [float(n) for n in _NUMBER_RE.findall(path.get("d") or "")]
    xs, ys = numbers[0::2], numbers[1::2]
    if not xs or not ys:
        return None
    match = _TRANSLATE_RE.search(path.get("transform") or "")
    dx, dy = (float(match.group(1)), float(match.group(2))) if match else (0.0, 0.0)
    return (min(xs) + dx, min(ys) + dy, max(xs) + dx, max(ys) + dy)


def _touching_groups(
    paths: list[etree._Element], tolerance: float = 1.0
) -> list[list[etree._Element]]:
    """Cluster same-colour shapes that touch, so each letter stays its own object.

    The tracer breaks a single letter into several fragments, but merging a
    whole colour into one path goes too far the other way: a word becomes one
    object you cannot pick letters out of. Grouping by overlapping bounds
    keeps separate glyphs separate while still fusing the pieces of each.

    Bounds overlap is a deliberate approximation -- two tightly kerned letters
    whose boxes intersect will merge. That is far less disruptive than either
    extreme.
    """
    boxes = [(path, _path_bounds(path)) for path in paths]
    usable = [(path, box) for path, box in boxes if box is not None]

    parent = list(range(len(usable)))

    def find(i: int) -> int:
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    def union(a: int, b: int) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[rb] = ra

    for i in range(len(usable)):
        ax0, ay0, ax1, ay1 = usable[i][1]
        for j in range(i + 1, len(usable)):
            bx0, by0, bx1, by1 = usable[j][1]
            if (
                ax0 - tolerance <= bx1
                and bx0 - tolerance <= ax1
                and ay0 - tolerance <= by1
                and by0 - tolerance <= ay1
            ):
                union(i, j)

    clusters: OrderedDict[int, list[etree._Element]] = OrderedDict()
    for index, (path, _) in enumerate(usable):
        clusters.setdefault(find(index), []).append(path)
    groups = list(clusters.values())
    groups.extend([path] for path, box in boxes if box is None)
    return groups


def _combine_by_color(
    root: etree._Element, paths: list[etree._Element], mode: str
) -> int:
    """Fuse all shapes sharing a fill into one path element.

    The tracer emits every shape separately, so a six-colour illustration can
    arrive in an editor as hundreds of objects -- one real case opened in
    CorelDRAW as "Group of 761 Objects", which is unusable for selecting or
    recolouring. Subpaths of one path render identically but count as a single
    object, so this collapses the file to roughly one object per colour.
    """
    by_fill: OrderedDict[str, list[etree._Element]] = OrderedDict()
    for path in paths:
        fill = path.get("fill")
        if not fill or fill == "none":
            continue
        by_fill.setdefault(fill, []).append(path)

    if mode == "colors":
        groups = list(by_fill.values())
    else:
        groups = [g for members in by_fill.values() for g in _touching_groups(members)]

    combined = 0
    for members in groups:
        if len(members) < 2:
            continue
        pieces: list[str] = []
        for path in members:
            data = path.get("d") or ""
            transform = path.get("transform") or ""
            match = _TRANSLATE_RE.search(transform)
            dx, dy = (float(match.group(1)), float(match.group(2))) if match else (0.0, 0.0)
            if transform and not match:
                pieces = []  # unexpected transform; do not risk moving artwork
                break
            shifted = _shift_path_data(data, dx, dy)
            if shifted is None:
                pieces = []
                break
            pieces.append(shifted)
        if not pieces:
            continue

        keeper = members[0]
        keeper.set("d", "".join(pieces))
        keeper.attrib.pop("transform", None)
        # Subpaths traced independently have no consistent winding direction,
        # so the default nonzero rule would fill counters and holes solid.
        keeper.set("fill-rule", "evenodd")
        for extra in members[1:]:
            parent = extra.getparent()
            if parent is not None:
                parent.remove(extra)
        combined += len(members) - 1
    return combined



# --- curve smoothing ---------------------------------------------------------
#
# The tracer puts a node wherever the pixel boundary turns, so a boundary that
# wobbles by a pixel gets a node for every wobble and the curve visibly
# notches. Nothing upstream can fix that: at the scale of one source pixel,
# where the boundary sits was decided by rounding, not by the artwork.
#
# So the notches are taken out of the curve itself. Each node is nudged toward
# the line between its neighbours -- never further than half a source pixel,
# which is smaller than the uncertainty that put it there -- and the segments
# are refitted through the result. Corners are found first and held still, so
# a letter keeps its joins and a logo keeps its right angles.

# A node whose tangent turns by more than this is a corner and is left alone.
# Kept below 90 so a right angle is always a corner.
_SMOOTH_CORNER_DEGREES = 60.0


def _segments(d: str) -> list[tuple[bool, list[list[float]], list[float]]] | None:
    """Split path data into subpaths of cubic segments. None if unsupported.

    Every segment comes back as ``[c1x, c1y, c2x, c2y, x, y]`` -- a line gets
    control points along its own chord -- so the rest of the code has one
    shape to deal with.
    """
    subpaths: list[tuple[bool, list[list[float]], list[float]]] = []
    current: list[list[float]] = []
    start: list[float] | None = None
    here: list[float] | None = None
    closed = False

    for command, body in _COMMAND_RE.findall(d):
        if command not in _PAIRS_PER_COMMAND:
            return None
        numbers = [float(n) for n in _NUMBER_RE.findall(body)]
        if command == "Z":
            closed = True
            continue
        if len(numbers) % 2:
            return None
        if command == "M":
            if current and start is not None:
                subpaths.append((closed, current, start))
            closed = False
            start = here = numbers[:2]
            current = []
            numbers = numbers[2:]
            command = "L"
        if here is None:
            return None
        step = _PAIRS_PER_COMMAND[command] * 2
        if command == "Q":
            return None  # quadratics are not emitted by the tracer
        for index in range(0, len(numbers), step):
            chunk = numbers[index : index + step]
            if len(chunk) < step:
                return None
            if command == "L":
                end = chunk
                c1 = [here[0] + (end[0] - here[0]) / 3, here[1] + (end[1] - here[1]) / 3]
                c2 = [here[0] + 2 * (end[0] - here[0]) / 3, here[1] + 2 * (end[1] - here[1]) / 3]
                current.append(c1 + c2 + end)
            else:
                current.append(list(chunk))
            here = current[-1][4:6]
    if current and start is not None:
        subpaths.append((closed, current, start))
    return subpaths


def _turn_degrees(before: list[float], node: list[float], after: list[float]) -> float:
    ax, ay = node[0] - before[0], node[1] - before[1]
    bx, by = after[0] - node[0], after[1] - node[1]
    if (ax or ay) and (bx or by):
        cross = ax * by - ay * bx
        dot = ax * bx + ay * by
        return abs(math.degrees(math.atan2(cross, dot)))
    return 0.0


# How much outline either side of a node is looked at when deciding whether it
# is a corner, in source pixels. Long enough to add a split corner back
# together, short enough that a gentle curve does not accumulate into one.
_CORNER_SPAN = 3.0


def _corner_flags(
    segments: list[list[float]], count: int, span: float
) -> list[bool]:
    """Which nodes the curve genuinely turns at, rather than merely wobbling.

    Comparing the two handles at a node is not enough. The tracer often splits
    one corner across two nodes -- a right angle came back as a pair of
    44-degree turns, neither of which looks like a corner on its own, and
    smoothing duly rounded it off. So the direction is measured across a span
    of outline either side instead, which adds a split corner back together
    and averages out a wobble at the same time.
    """
    nodes = [segment[4:6] for segment in segments]

    def reach(index: int, step: int) -> list[float]:
        travelled = 0.0
        cursor = index
        for _ in range(count):
            following = (cursor + step) % count
            travelled += math.dist(nodes[cursor], nodes[following])
            cursor = following
            if travelled >= span:
                break
        return nodes[cursor]

    flags = []
    for index in range(count):
        before, after = reach(index, -1), reach(index, 1)
        flags.append(
            _turn_degrees(before, nodes[index], after) > _SMOOTH_CORNER_DEGREES
        )
    return flags


# How far the simplified curve may stray from the one the tracer produced, in
# source pixels. Every node the tracer emitted marks somewhere the pixel
# boundary turned, so a run of them along one gentle curve is a run of chances
# to wobble; fusing those into a single segment is what finally makes a long
# edge read as one stroke. Kept below half a pixel so the outline still lands
# where the tracer found it.
_SIMPLIFY_TOLERANCE = 1.2

# Points sampled along a pair of segments when measuring how far their
# replacement strays. Enough to catch a bulge in the middle without making the
# check the expensive part of the pass.
_SIMPLIFY_SAMPLES = 8


def _cubic_at(segment: list[float], start: list[float], t: float) -> tuple[float, float]:
    """A point on the cubic that runs from *start* through *segment*."""
    u = 1.0 - t
    a, b, c, d = u * u * u, 3 * u * u * t, 3 * u * t * t, t * t * t
    return (
        a * start[0] + b * segment[0] + c * segment[2] + d * segment[4],
        a * start[1] + b * segment[1] + c * segment[3] + d * segment[5],
    )


def _fuse(
    first: list[float], second: list[float], start: list[float]
) -> list[float] | None:
    """One cubic covering both, or None if the two cannot be spanned.

    The join between them lands at some fraction of the way along the pair, so
    each outer handle is stretched by that fraction to cover the whole span.
    """
    middle = first[4:6]
    span = math.dist(start, middle) + math.dist(middle, second[4:6])
    if not span:
        return None
    share = math.dist(start, middle) / span
    if share <= 0.0 or share >= 1.0:
        return None
    return [
        start[0] + (first[0] - start[0]) / share,
        start[1] + (first[1] - start[1]) / share,
        second[4] + (second[2] - second[4]) / (1.0 - share),
        second[5] + (second[3] - second[5]) / (1.0 - share),
        second[4],
        second[5],
    ]


def _strays(
    fused: list[float],
    first: list[float],
    second: list[float],
    start: list[float],
    tolerance: float,
) -> bool:
    """True if the fused curve wanders further than *tolerance* from the pair."""
    for index in range(1, _SIMPLIFY_SAMPLES):
        t = index / _SIMPLIFY_SAMPLES
        if t < 0.5:
            original = _cubic_at(first, start, t * 2)
        else:
            original = _cubic_at(second, first[4:6], (t - 0.5) * 2)
        if math.dist(original, _cubic_at(fused, start, t)) > tolerance:
            return True
    return False


def _simplify_subpath(
    segments: list[list[float]], corner: list[bool], tolerance: float
) -> tuple[list[list[float]], list[bool]] | None:
    """Fuse neighbouring segments wherever one curve will do for both."""
    count = len(segments)
    if count < 5:
        return None

    keep: list[list[float]] = []
    keep_corner: list[bool] = []
    index = 0
    fused_any = False
    while index < count:
        segment = segments[index]
        following = index + 1
        # The node between the pair is the one that would disappear, so it has
        # to be an ordinary node, and the pair has to stay inside the subpath.
        if following < count and not corner[index]:
            start = segments[index - 1][4:6] if index else segments[-1][4:6]
            fused = _fuse(segment, segments[following], start)
            if fused is not None and not _strays(
                fused, segment, segments[following], start, tolerance
            ):
                keep.append(fused)
                keep_corner.append(corner[following])
                index += 2
                fused_any = True
                continue
        keep.append(list(segment))
        keep_corner.append(corner[index])
        index += 1
    return (keep, keep_corner) if fused_any else None


def _smooth_subpath(
    segments: list[list[float]], closed: bool, tolerance: float, span: float
) -> list[list[float]]:
    """Fuse neighbouring segments until one curve will not do for two."""
    count = len(segments)
    if count < 5 or not closed or not tolerance:
        return segments

    corners = _corner_flags(segments, count, span)
    while True:
        fused = _simplify_subpath(segments, corners, tolerance)
        if fused is None:
            return segments
        segments, corners = fused


def _smooth_path_data(d: str, tolerance: float, span: float) -> str | None:
    """Rewrite path data with fewer, longer segments. None if left alone."""
    subpaths = _segments(d)
    if not subpaths:
        return None
    out = []
    for closed, segments, start in subpaths:
        smoothed = _smooth_subpath(segments, closed, tolerance, span)
        out.append("M" + " ".join(_fmt(v) for v in start))
        for segment in smoothed:
            out.append("C" + " ".join(_fmt(v) for v in segment))
        if closed:
            out.append("Z")
    return "".join(out)


def _smooth_curves(paths: list[etree._Element], supersample: int = 1) -> int:
    """Take the waviness out of every path that will take it.

    Both measurements are in source pixels, so they scale with whatever
    resolution the bitmap was traced at.
    """
    tolerance = _SIMPLIFY_TOLERANCE * supersample
    span = _CORNER_SPAN * supersample
    smoothed = 0
    for path in paths:
        data = path.get("d")
        if not data:
            continue
        rewritten = _smooth_path_data(data, tolerance, span)
        if rewritten:
            path.set("d", rewritten)
            smoothed += 1
    return smoothed


# --- gradient fills ----------------------------------------------------------
#
# The tracer only ever emits flat fills, so shaded artwork has nowhere to go:
# banding it into narrow strips reads as stripes, and collapsing it to one
# colour throws the shading away. Neither is what the artwork says.
#
# But the shading in this kind of artwork is almost always a straight ramp --
# fitting one to a shaded sticker's lettering left a residual of 0.29 out of
# 255 -- and SVG has had a construct for exactly that since the beginning. So
# each flat fill is checked against the pixels it came from, and where those
# pixels lie on a ramp the fill is replaced by a linearGradient along it.

# How far the pixels may sit from the fitted ramp, per channel, before the
# region is called flat-and-noisy rather than shaded.
_GRADIENT_MAX_RESIDUAL = 8.0

# How much the colour has to travel from one end of the region to the other to
# be worth a gradient at all. Below this it is a flat fill with a slight cast.
_GRADIENT_MIN_TRAVEL = 24.0

# Sampled pixels needed before a fit is trusted.
_GRADIENT_MIN_SAMPLES = 200

# Every Nth pixel is sampled. The fit is over thousands of them either way.
_GRADIENT_SAMPLE_STEP = 3


def _fit_ramp(samples: list[tuple[int, int, tuple[int, int, int]]]):
    """Least-squares fit of colour against position. None if it is not a ramp.

    Returns the colour at each end of the region along the direction the
    colour actually travels, plus those two points.
    """
    count = len(samples)
    if count < _GRADIENT_MIN_SAMPLES:
        return None
    mean_x = sum(s[0] for s in samples) / count
    mean_y = sum(s[1] for s in samples) / count
    sxx = sum((s[0] - mean_x) ** 2 for s in samples)
    syy = sum((s[1] - mean_y) ** 2 for s in samples)
    sxy = sum((s[0] - mean_x) * (s[1] - mean_y) for s in samples)
    det = sxx * syy - sxy * sxy
    if not det:
        return None

    middle = []
    slopes = []
    residuals = []
    for channel in range(3):
        mean_c = sum(s[2][channel] for s in samples) / count
        sxc = sum((s[0] - mean_x) * (s[2][channel] - mean_c) for s in samples)
        syc = sum((s[1] - mean_y) * (s[2][channel] - mean_c) for s in samples)
        gx = (syy * sxc - sxy * syc) / det
        gy = (sxx * syc - sxy * sxc) / det
        error = sum(
            (s[2][channel] - (mean_c + gx * (s[0] - mean_x) + gy * (s[1] - mean_y))) ** 2
            for s in samples
        )
        middle.append(mean_c)
        slopes.append((gx, gy))
        residuals.append((error / count) ** 0.5)

    if max(residuals) > _GRADIENT_MAX_RESIDUAL:
        return None

    # The direction the colour travels is the average of the three channel
    # gradients, weighted by how fast each one moves.
    dx = sum(g[0] for g in slopes)
    dy = sum(g[1] for g in slopes)
    length = math.hypot(dx, dy)
    if not length:
        return None
    dx, dy = dx / length, dy / length

    # How far along that direction the region actually reaches.
    reach = [(s[0] - mean_x) * dx + (s[1] - mean_y) * dy for s in samples]
    low, high = min(reach), max(reach)
    if high <= low:
        return None

    def colour_at(distance: float) -> tuple[int, int, int]:
        return tuple(  # type: ignore[return-value]
            max(0, min(255, round(middle[c] + (slopes[c][0] * dx + slopes[c][1] * dy) * distance)))
            for c in range(3)
        )

    start, end = colour_at(low), colour_at(high)
    travel = sum((a - b) ** 2 for a, b in zip(start, end)) ** 0.5
    if travel < _GRADIENT_MIN_TRAVEL:
        return None
    return (
        start,
        end,
        (mean_x + dx * low, mean_y + dy * low),
        (mean_x + dx * high, mean_y + dy * high),
    )


def _shaded_fills(
    source: Image.Image, fills: list[str], step: int = _GRADIENT_SAMPLE_STEP
) -> dict[str, tuple]:
    """Which of *fills* cover a ramp in *source*, and the ramp that fits."""
    targets = [(fill, _rgb(fill)) for fill in fills]
    targets = [(fill, rgb) for fill, rgb in targets if rgb is not None]
    if len(targets) < 2:
        return {}

    grouped: dict[str, list[tuple[int, int, tuple[int, int, int]]]] = {
        fill: [] for fill, _ in targets
    }
    pixels = source.load()
    width, height = source.size
    for y in range(0, height, step):
        for x in range(0, width, step):
            colour = pixels[x, y][:3]
            nearest = min(
                targets, key=lambda t: sum((a - b) ** 2 for a, b in zip(t[1], colour))
            )
            grouped[nearest[0]].append((x, y, colour))

    ramps = {}
    for fill, samples in grouped.items():
        fitted = _fit_ramp(samples)
        if fitted is not None:
            ramps[fill] = fitted
    return ramps


def _apply_gradients(
    root: etree._Element, paths: list[etree._Element], source: Image.Image
) -> int:
    """Replace every flat fill that covers a ramp with a linearGradient."""
    fills = sorted({p.get("fill") for p in paths if p.get("fill") not in (None, "none")})
    ramps = _shaded_fills(source, fills)  # type: ignore[arg-type]
    if not ramps:
        return 0

    defs = etree.Element(_q("defs"))
    for index, (fill, (start, end, first, last)) in enumerate(sorted(ramps.items())):
        gradient = etree.SubElement(defs, _q("linearGradient"))
        gradient.set("id", f"shade{index}")
        gradient.set("gradientUnits", "userSpaceOnUse")
        gradient.set("x1", _fmt(first[0]))
        gradient.set("y1", _fmt(first[1]))
        gradient.set("x2", _fmt(last[0]))
        gradient.set("y2", _fmt(last[1]))
        for offset, colour in ((0.0, start), (1.0, end)):
            stop = etree.SubElement(gradient, _q("stop"))
            stop.set("offset", _fmt(offset))
            stop.set("stop-color", "#%02x%02x%02x" % colour)
        for path in paths:
            if path.get("fill") == fill:
                path.set("fill", f"url(#shade{index})")
                if path.get("stroke") == fill:
                    path.set("stroke", "#%02x%02x%02x" % start)
    root.insert(0, defs)
    return len(ramps)


def _group_by_color(root: etree._Element, paths: list[etree._Element]) -> None:
    """Collect same-coloured shapes into one <g>, the way designers expect."""
    buckets: OrderedDict[str, list[etree._Element]] = OrderedDict()
    for path in paths:
        key = path.get("fill") or path.get("stroke") or "none"
        buckets.setdefault(key, []).append(path)

    for color, members in buckets.items():
        group = etree.SubElement(root, _q("g"))
        group.set("data-color", color)
        group.set("id", "color-" + color.lstrip("#"))
        for path in members:
            root.remove(path)
            group.append(path)


def _add_background(root: etree._Element, params: VectorizeParams, w: int, h: int) -> None:
    background = params.output_background
    if not background or background == "transparent":
        return
    rect = etree.Element(_q("rect"))
    rect.set("x", "0")
    rect.set("y", "0")
    rect.set("width", str(w))
    rect.set("height", str(h))
    rect.set("fill", background)
    root.insert(0, rect)


def _add_watermark(root: etree._Element, params: VectorizeParams, w: int, h: int) -> None:
    """Mark non-production results so they cannot ship unnoticed."""
    if not params.watermark:
        return

    label = params.mode.upper()
    group = etree.SubElement(root, _q("g"))
    group.set("id", "watermark")
    group.set("opacity", "0.28")
    group.set("pointer-events", "none")

    font_size = max(12.0, min(w, h) / 8.0)
    step_x = font_size * 9.0
    step_y = font_size * 5.0
    rows = int(h / step_y) + 2
    cols = int(w / step_x) + 2

    for row in range(rows):
        for col in range(cols):
            x = col * step_x - (step_x / 2 if row % 2 else 0)
            y = row * step_y
            text = etree.SubElement(group, _q("text"))
            text.set("x", _fmt(x))
            text.set("y", _fmt(y))
            text.set("font-family", "Helvetica, Arial, sans-serif")
            text.set("font-size", _fmt(font_size))
            text.set("font-weight", "bold")
            text.set("fill", "#808080")
            text.set("transform", f"rotate(-30 {_fmt(x)} {_fmt(y)})")
            text.text = label


def _set_geometry(
    root: etree._Element,
    params: VectorizeParams,
    source_w: int,
    source_h: int,
    for_print: bool,
    supersample: int = 1,
) -> tuple[float, float]:
    """Give the document a viewBox and a real-world size.

    The viewBox always stays in tracer pixel space, so scaling is purely a
    presentation concern and never touches the path data. When the bitmap was
    traced at a multiple of its own resolution, that multiple divides out here
    -- the extra pixels bought accuracy, not size.
    """
    root.set("viewBox", f"0 0 {source_w} {source_h}")
    root.set("preserveAspectRatio", "xMidYMid meet")

    target_w, target_h = params.target_size_px(
        source_w / supersample, source_h / supersample
    )

    if for_print:
        # PDF/EPS consumers think in points; emitting points keeps the
        # physical size exact rather than relying on a 96dpi assumption
        # further down the toolchain.
        root.set("width", f"{_fmt(units.px_to_points(target_w))}pt")
        root.set("height", f"{_fmt(units.px_to_points(target_h))}pt")
    elif params.output_size_unit == "px":
        root.set("width", _fmt(target_w))
        root.set("height", _fmt(target_h))
    else:
        unit = params.output_size_unit
        root.set("width", f"{_fmt(units.from_pixels(target_w, unit))}{unit}")
        root.set("height", f"{_fmt(units.from_pixels(target_h, unit))}{unit}")

    return target_w, target_h


def build(
    svg_text: str,
    params: VectorizeParams,
    source_w: int,
    source_h: int,
    *,
    for_print: bool = False,
    palette: list[str] | None = None,
    supersample: int = 1,
    shading: "Image.Image | None" = None,
) -> tuple[bytes, dict[str, float | int]]:
    """Post-process raw tracer SVG into the final document.

    Returns the serialized SVG and geometry metadata for response headers.
    """
    root = parse(svg_text)

    # Drop the tracer's own generator comment; we add our own below. The
    # comment sits outside the root element, so it has no parent to remove
    # it from and is simply dropped when we re-serialize from `root`.
    for node in root.xpath("//comment()"):
        parent = node.getparent()
        if parent is not None:
            parent.remove(node)

    paths = _paths(root)
    traced_shapes = len(paths)
    if not paths:
        raise VectorizationFailed(
            "No shapes were found. The image may be blank, or "
            "processing.shapes.min_area_px may be filtering everything out."
        )

    # A pinned palette is a promise; honour it before anything else looks at
    # the colours. A palette derived from the artwork gets the same treatment:
    # the pixels were mapped onto it, so the fills have to be too, or the
    # tracer's cluster averages reintroduce the very bands it removed.
    effective_palette = params.processing_palette or palette
    if effective_palette:
        _snap_to_palette(paths, effective_palette)
    merged = _merge_similar_colors(paths, params.processing_color_merge)
    _smooth_curves(paths, supersample)
    # Flat fills that cover a ramp become gradients. Only worth asking when
    # the colours were left as the artwork had them: a palette means the
    # caller or the detector already decided the artwork is flat.
    shaded = 0
    if shading is not None and not effective_palette:
        shaded = _apply_gradients(root, paths, shading)
    _apply_draw_style(paths, params)
    _apply_gap_filler(paths, params)
    _add_background(root, params, source_w, source_h)
    combined = "none"
    if params.output_combine_paths != "none":
        _combine_by_color(root, paths, params.output_combine_paths)
        paths = _paths(root)
        combined = params.output_combine_paths
    if params.output_group_by == "color":
        _group_by_color(root, paths)
    target_w, target_h = _set_geometry(
        root, params, source_w, source_h, for_print, supersample
    )
    _add_watermark(root, params, source_w, source_h)

    root.set("version", "1.1")

    # Serialize the element rather than the tree: the tracer's generator
    # comment is a sibling of the root at document level, which lxml cannot
    # detach, so writing from `root` is what actually drops it.
    body = _PROLOGUE + etree.tostring(
        root,
        xml_declaration=False,
        encoding="UTF-8",
        pretty_print=True,
    )

    meta: dict[str, float | int] = {
        "paths": len(_paths(root)),
        "shapes": traced_shapes,
        "combined": combined,
        "gradients": shaded,
        "source_width": source_w,
        "source_height": source_h,
        "output_width": target_w,
        "output_height": target_h,
    }
    return body, meta


def count_colors(svg_text: str) -> int:
    root = parse(svg_text)
    return len({p.get("fill") for p in _paths(root) if p.get("fill")})
