"""SVG post-processing.

The tracer emits a bare list of filled paths. Everything that turns that
into a usable, editable document happens here: a proper coordinate system,
physical output size, draw styles, colour grouping, seam removal and
watermarking.
"""

from __future__ import annotations

import math
import re
from collections import OrderedDict

from lxml import etree
from PIL import Image

from app.core.errors import VectorizationFailed
from app.schemas.params import VectorizeParams
from app.utils import units

SVG_NS = "http://www.w3.org/2000/svg"
NSMAP = {None: SVG_NS}

_NUMBER_RE = re.compile(r"-?\d+\.?\d*")

_PROLOGUE = (
    b'<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
    b"<!-- Generated by Python Vector API -->\n"
)


def _q(tag: str) -> str:
    return f"{{{SVG_NS}}}{tag}"


def _fmt(value: float) -> str:
    """Compact number formatting: 300.0 -> '300', 12.3456 -> '12.346'."""
    rounded = round(value, 3)
    if rounded == int(rounded):
        return str(int(rounded))
    return f"{rounded:g}"


def parse(svg_text: str) -> etree._Element:
    parser = etree.XMLParser(remove_blank_text=False, resolve_entities=False, huge_tree=False)
    try:
        return etree.fromstring(svg_text.encode("utf-8"), parser=parser)
    except etree.XMLSyntaxError as exc:  # pragma: no cover - tracer emits valid XML
        raise VectorizationFailed(f"The tracer produced invalid SVG: {exc}") from exc


def _paths(root: etree._Element) -> list[etree._Element]:
    return list(root.iter(_q("path")))


def _apply_draw_style(paths: list[etree._Element], params: VectorizeParams) -> None:
    """Re-express each shape as fill, outline, or bare edge."""
    style = params.output_draw_style
    if style == "fill_shapes":
        return

    width = _fmt(params.output_stroke_width)
    for path in paths:
        fill = path.get("fill", "#000000")
        path.set("fill", "none")
        path.set("stroke", "#000000" if style == "stroke_edges" else fill)
        path.set("stroke-width", width)
        path.set("stroke-linejoin", "round")
        path.set("stroke-linecap", "round")


def _apply_gap_filler(
    paths: list[etree._Element], params: VectorizeParams, covered: bool = False
) -> None:
    """Hide the hairline seams renderers leave between abutting shapes.

    Adjacent traced shapes share an edge exactly. Anti-aliasing each of them
    independently leaves both of them at partial coverage along that shared
    edge, so the backdrop shows through it — a dark line against a dark page,
    which is what made every letter look outlined in a viewer and in CorelDRAW.

    Two things make the seal work, and both were wrong before.

    It has to be **non-scaling**. The seam is one device pixel wide whatever the
    zoom, so a width in the artwork's own coordinates is the wrong unit for it:
    on a 3200-unit viewBox drawn 480px wide the old 0.35 covered 0.05 of a pixel
    and sealed nothing, while a value big enough to seal at that size would
    print as a fat halo. `vector-effect="non-scaling-stroke"` fixes the width in
    device space, so one value holds at 100% and at 6400%, and svgToPdf maps it
    onto a PDF line width of 0 — which PDF defines as the thinnest line the
    device can render, i.e. that same one pixel.

    And it has to be painted in the **blend of the two colours that meet**, not
    in each shape's own colour. Stroking a shape in its own fill grows it by
    half the stroke, so whichever shape is painted last wins the seam and the
    artwork dilates: measured, self-coloured seals sealed the leak but pushed
    coverage from +0.30pp to +0.87pp and cost 1.6 points of agreement with the
    source. The midpoint colour is what correct anti-aliasing would have put
    there anyway, so it covers the seam without moving the boundary either way.

    And once the seam backdrop is down, most edges must not be sealed at all.
    A seam reveals whatever lies behind it, which is now the dominant ink, so
    on any boundary where one side *is* that ink the backdrop already shows the
    right colour and a stroke there is pure damage: it lays a band of blend
    along an edge that was correct. That band is one device pixel wide where
    vector-effect is honoured, but Skia and several editors scale it with the
    zoom instead, which is what turned every black-on-cream edge of a traced
    botanical into a visible olive fringe at 14x.

    So when the canvas is covered, only the shapes that can actually show a
    wrong colour are sealed: the ones that neither are the dominant ink nor
    border it. Measured on the reference set, dropping the rest took agreement
    with the source from 0.412 to 0.140 on the logo and 0.545 to 0.432 on the
    layered artwork. The interior seams that still get sealed are what keeps
    the multi-ink samples from regressing at zoom, where removing every stroke
    instead cost them 0.061 and 0.074 at 3x.

    Where nothing covers the canvas -- a transparent background, or a source
    with alpha, where showing through is the point -- every shape is sealed as
    before, because a seam there reveals the page rather than an ink.
    """
    if not params.output_gap_filler_enabled:
        return
    if params.output_draw_style != "fill_shapes":
        return  # stroked output has no seams to hide

    width = _fmt(params.output_gap_filler_stroke_width)

    # Rank the fills by the area they cover. The most prominent one is the
    # ground almost every other shape sits on, so it is the colour on the far
    # side of most seams. A shape that genuinely borders something else gets a
    # slightly wrong blend on a one-pixel line, which is still far better than
    # letting the backdrop through.
    areas: dict[str, float] = {}
    for path in paths:
        fill = path.get("fill")
        if fill and fill != "none":
            areas[fill] = areas.get(fill, 0.0) + _filled_area(path)
    if not areas:
        return

    ranked = sorted(areas, key=lambda c: areas[c], reverse=True)
    ground = ranked[0]
    runner_up = ranked[1] if len(ranked) > 1 else ground

    at_risk = _seam_risks(paths, ground) if covered else None

    for path in paths:
        fill = path.get("fill")
        if not fill or fill == "none":
            continue
        if at_risk is not None and id(path) not in at_risk:
            continue
        # The ground's own neighbours are everything else, so pair it with the
        # next most prominent colour; on two-colour artwork both shapes then
        # seal with the same midpoint, which is what the seam actually is.
        other = runner_up if fill == ground else ground
        path.set("stroke", _blend(fill, other))
        path.set("stroke-width", width)
        path.set("stroke-linejoin", "round")
        path.set("vector-effect", "non-scaling-stroke")


def _canvas_is_covered(params: VectorizeParams, source_has_alpha: bool) -> bool:
    """True when something opaque is painted across the whole canvas.

    That is either the explicit background, or the ink laid down by
    _add_seam_backdrop. The conditions have to agree with that function, which
    steps aside for an explicit background and for a source with alpha.
    """
    background = params.output_background
    if background:
        return background != "transparent"
    if params.output_draw_style != "fill_shapes":
        return False
    return not source_has_alpha


def _seam_risks(paths: list[etree._Element], ground: str) -> set[int]:
    """Shapes whose seams the backdrop cannot repair, identified by id().

    A seam shows the dominant ink, so it is invisible wherever one side of the
    boundary already is that ink. What is left is the boundary between two
    other inks, and a shape can only sit on one of those if it is not the
    ground itself and it meets another shape that is not the ground either.

    Overlap is judged on bounding boxes, which is deliberately generous: two
    boxes that miss each other cannot share an edge, so nothing that needs
    sealing is dropped, while a shape sealed because its box happens to span
    another one costs only the hairline it would have carried anyway. Sorting
    by left edge lets the scan stop early, which matters on the busiest
    artwork in the corpus, where there are over a thousand shapes.
    """
    boxes: list[tuple[int, tuple[float, float, float, float]]] = []
    for path in paths:
        fill = path.get("fill")
        if not fill or fill == "none" or fill == ground:
            continue
        bounds = _path_bounds(path)
        if bounds is not None:
            boxes.append((id(path), bounds))
    boxes.sort(key=lambda item: item[1][0])

    at_risk: set[int] = set()
    for index, (key, a) in enumerate(boxes):
        for other, b in boxes[index + 1:]:
            if b[0] > a[2]:
                break  # sorted by left edge, so nothing further can overlap
            if a[1] <= b[3] and b[1] <= a[3]:
                at_risk.add(key)
                at_risk.add(other)
    return at_risk


def _blend(one: str, two: str) -> str:
    """Midpoint of two hex colours, falling back to the first if either is odd.

    This is the colour an anti-aliased boundary between the two would land on,
    which is why it is the right paint for a seam seal — see _apply_gap_filler.
    """
    a, b = _rgb(one), _rgb(two)
    if a is None or b is None:
        return one
    return "#" + "".join(f"{(x + y) // 2:02x}" for x, y in zip(a, b))


def _rgb(value: str) -> tuple[int, int, int] | None:
    value = value.strip()
    if not value.startswith("#") or len(value) not in (4, 7):
        return None
    if len(value) == 4:
        value = "#" + "".join(ch * 2 for ch in value[1:])
    try:
        return tuple(int(value[i : i + 2], 16) for i in (1, 3, 5))  # type: ignore[return-value]
    except ValueError:
        return None


def _filled_area(path: etree._Element) -> float:
    """Approximate enclosed area, used to rank colours by prominence.

    Shoelace over the path's control points. It is only an approximation for
    curves, but the important property is that it measures what a shape
    *covers* -- a bounding box does not, and a thin ring's box is as big as
    the shape it surrounds, which would rank a transition band above the fill
    it borders and merge colours in exactly the wrong direction.
    """
    numbers = [float(n) for n in _NUMBER_RE.findall(path.get("d") or "")]
    xs, ys = numbers[0::2], numbers[1::2]
    count = min(len(xs), len(ys))
    if count < 3:
        return 0.0
    total = 0.0
    for i in range(count):
        j = (i + 1) % count
        total += xs[i] * ys[j] - xs[j] * ys[i]
    return abs(total) / 2.0


def _resolve_blend(
    colour: tuple[int, int, int], targets: list[tuple[str, tuple[int, int, int]]]
) -> str:
    """Decide which palette colour a traced fill really belongs to.

    The tracer averages the pixels inside each cluster, so a cluster straddling
    a boundary comes back as a blend of the two colours either side. Snapping
    such a blend to the *nearest* palette entry is wrong, and wrong in a way
    that is very visible: the midpoint of a dark charcoal and a cream sits
    close to a sage green, so every letter grew a green outline that exists
    nowhere in the artwork.

    Instead, find the pair of palette colours whose mixture best explains the
    blend, and award it to whichever of the two dominates. A dark/cream blend
    resolves to dark or cream -- never to some third colour that merely
    happens to sit nearby in RGB space.
    """
    best_error = float("inf")
    best_name = targets[0][0]
    for i, (name_a, a) in enumerate(targets):
        for name_b, b in targets[i:]:
            delta = tuple(bc - ac for ac, bc in zip(a, b))
            length = sum(d * d for d in delta)
            if length == 0:
                weight = 0.0
            else:
                # Project the blend onto the a->b line, clamped to the segment.
                weight = sum(
                    (c - ac) * d for c, ac, d in zip(colour, a, delta)
                ) / length
                weight = max(0.0, min(1.0, weight))
            mixed = tuple(ac + weight * d for ac, d in zip(a, delta))
            error = sum((c - m) ** 2 for c, m in zip(colour, mixed))
            if error < best_error:
                best_error = error
                best_name = name_b if weight > 0.5 else name_a
    return best_name


def _snap_to_palette(paths: list[etree._Element], palette: list[str]) -> int:
    """Force every fill onto the requested palette.

    The bitmap handed to the tracer already contains exactly these colours,
    but the tracer averages within clusters, so ask for six colours and two
    hundred come out. The extras show up in an editor as ghost layers beside
    the real shapes, so they have to be resolved back to the palette.
    """
    targets = [(colour, _rgb(colour)) for colour in palette]
    targets = [(colour, rgb) for colour, rgb in targets if rgb is not None]
    if not targets:
        return 0

    snapped = 0
    cache: dict[str, str] = {}
    for path in paths:
        fill = path.get("fill")
        if not fill or fill == "none":
            continue
        if fill not in cache:
            source = _rgb(fill)
            if source is None:
                continue
            cache[fill] = _resolve_blend(source, targets)
        nearest = cache[fill]
        if nearest != fill:
            snapped += 1
        path.set("fill", nearest)
        if path.get("stroke") and path.get("stroke") != "none":
            path.set("stroke", nearest)  # gap filler tracks the fill
    return snapped


def _merge_similar_colors(paths: list[etree._Element], threshold: float) -> int:
    """Snap near-duplicate fills onto the dominant colour they sit beside.

    Anti-aliasing between two flat regions leaves a transition band, and the
    tracer emits it as its own shapes -- pale lumps sitting between a dark
    stroke and its fill. Worse, it often splits that band into fills a single
    RGB unit apart (#4d3e48 next to #4d3f48). No tracer setting merges those,
    because to the tracer they really are different colours.

    So collapse them afterwards: rank fills by how much area they cover, then
    remap each minor colour onto the nearest more-prominent one within
    *threshold* RGB distance.
    """
    if threshold <= 0:
        return 0

    area_by_color: dict[str, float] = {}
    for path in paths:
        fill = path.get("fill")
        if fill and fill != "none":
            area_by_color[fill] = area_by_color.get(fill, 0.0) + _filled_area(path)

    # Most prominent first, so minor colours dissolve into major ones and
    # never the other way round.
    ranked = sorted(area_by_color, key=lambda c: area_by_color[c], reverse=True)
    remap: dict[str, str] = {}
    for index, color in enumerate(ranked):
        source = _rgb(color)
        if source is None:
            continue
        best, best_distance = None, threshold
        for major in ranked[:index]:
            target = _rgb(remap.get(major, major))
            if target is None:
                continue
            distance = sum((a - b) ** 2 for a, b in zip(source, target)) ** 0.5
            if distance <= best_distance:
                best, best_distance = remap.get(major, major), distance
        if best is not None:
            remap[color] = best

    if not remap:
        return 0
    for path in paths:
        fill = path.get("fill")
        if fill in remap:
            path.set("fill", remap[fill])
            if path.get("stroke") == fill:  # gap filler tracks the fill
                path.set("stroke", remap[fill])
    return len(remap)


_COMMAND_RE = re.compile(r"([MLCQZmlcqz])([^MLCQZmlcqz]*)")

# Coordinate pairs consumed by each absolute path command.
_PAIRS_PER_COMMAND = {"M": 1, "L": 1, "C": 3, "Q": 2, "Z": 0}


def _shift_path_data(d: str, dx: float, dy: float) -> str | None:
    """Bake a translate into absolute path data. None if it is not safe to.

    The tracer emits a per-shape ``transform="translate(x,y)"``. Combining
    shapes into one element means their coordinates have to live in the same
    space, so the offset is folded into the numbers here.
    """
    out: list[str] = []
    for command, body in _COMMAND_RE.findall(d):
        if command not in _PAIRS_PER_COMMAND:
            return None  # relative command: leave this path alone
        if command == "Z":
            out.append("Z")
            continue
        numbers = [float(n) for n in _NUMBER_RE.findall(body)]
        if len(numbers) % 2:
            return None
        shifted = []
        for i in range(0, len(numbers), 2):
            shifted.append(_fmt(numbers[i] + dx))
            shifted.append(_fmt(numbers[i + 1] + dy))
        out.append(command + " ".join(shifted))
    return "".join(out)


_TRANSLATE_RE = re.compile(
    r"translate\(\s*(-?\d+\.?\d*)[ ,]+(-?\d+\.?\d*)\s*\)"
)


def _path_bounds(path: etree._Element) -> tuple[float, float, float, float] | None:
    """Bounding box in document space, with the shape's translate applied."""
    numbers = [float(n) for n in _NUMBER_RE.findall(path.get("d") or "")]
    xs, ys = numbers[0::2], numbers[1::2]
    if not xs or not ys:
        return None
    match = _TRANSLATE_RE.search(path.get("transform") or "")
    dx, dy = (float(match.group(1)), float(match.group(2))) if match else (0.0, 0.0)
    return (min(xs) + dx, min(ys) + dy, max(xs) + dx, max(ys) + dy)


def _touching_groups(
    paths: list[etree._Element], tolerance: float = 1.0
) -> list[list[etree._Element]]:
    """Cluster same-colour shapes that touch, so each letter stays its own object.

    The tracer breaks a single letter into several fragments, but merging a
    whole colour into one path goes too far the other way: a word becomes one
    object you cannot pick letters out of. Grouping by overlapping bounds
    keeps separate glyphs separate while still fusing the pieces of each.

    Bounds overlap is a deliberate approximation -- two tightly kerned letters
    whose boxes intersect will merge. That is far less disruptive than either
    extreme.
    """
    boxes = [(path, _path_bounds(path)) for path in paths]
    usable = [(path, box) for path, box in boxes if box is not None]

    parent = list(range(len(usable)))

    def find(i: int) -> int:
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    def union(a: int, b: int) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[rb] = ra

    for i in range(len(usable)):
        ax0, ay0, ax1, ay1 = usable[i][1]
        for j in range(i + 1, len(usable)):
            bx0, by0, bx1, by1 = usable[j][1]
            if (
                ax0 - tolerance <= bx1
                and bx0 - tolerance <= ax1
                and ay0 - tolerance <= by1
                and by0 - tolerance <= ay1
            ):
                union(i, j)

    clusters: OrderedDict[int, list[etree._Element]] = OrderedDict()
    for index, (path, _) in enumerate(usable):
        clusters.setdefault(find(index), []).append(path)
    groups = list(clusters.values())
    groups.extend([path] for path, box in boxes if box is None)
    return groups


def _combine_by_color(
    root: etree._Element, paths: list[etree._Element], mode: str
) -> int:
    """Fuse all shapes sharing a fill into one path element.

    The tracer emits every shape separately, so a six-colour illustration can
    arrive in an editor as hundreds of objects -- one real case opened in
    CorelDRAW as "Group of 761 Objects", which is unusable for selecting or
    recolouring. Subpaths of one path render identically but count as a single
    object, so this collapses the file to roughly one object per colour.
    """
    by_fill: OrderedDict[str, list[etree._Element]] = OrderedDict()
    for path in paths:
        fill = path.get("fill")
        if not fill or fill == "none":
            continue
        by_fill.setdefault(fill, []).append(path)

    if mode == "colors":
        groups = list(by_fill.values())
    else:
        groups = [g for members in by_fill.values() for g in _touching_groups(members)]

    combined = 0
    for members in groups:
        if len(members) < 2:
            continue
        pieces: list[str] = []
        for path in members:
            data = path.get("d") or ""
            transform = path.get("transform") or ""
            match = _TRANSLATE_RE.search(transform)
            dx, dy = (float(match.group(1)), float(match.group(2))) if match else (0.0, 0.0)
            if transform and not match:
                pieces = []  # unexpected transform; do not risk moving artwork
                break
            shifted = _shift_path_data(data, dx, dy)
            if shifted is None:
                pieces = []
                break
            pieces.append(shifted)
        if not pieces:
            continue

        keeper = members[0]
        keeper.set("d", "".join(pieces))
        keeper.attrib.pop("transform", None)
        # Subpaths traced independently have no consistent winding direction,
        # so the default nonzero rule would fill counters and holes solid.
        keeper.set("fill-rule", "evenodd")
        for extra in members[1:]:
            parent = extra.getparent()
            if parent is not None:
                parent.remove(extra)
        combined += len(members) - 1
    return combined



# --- curve smoothing ---------------------------------------------------------
#
# The tracer puts a node wherever the pixel boundary turns, so a boundary that
# wobbles by a pixel gets a node for every wobble and the curve visibly
# notches. Nothing upstream can fix that: at the scale of one source pixel,
# where the boundary sits was decided by rounding, not by the artwork.
#
# So the notches are taken out of the curve itself. Each node is nudged toward
# the line between its neighbours -- never further than half a source pixel,
# which is smaller than the uncertainty that put it there -- and the segments
# are refitted through the result. Corners are found first and held still, so
# a letter keeps its joins and a logo keeps its right angles.

# A node whose tangent turns by more than this is a corner and is left alone.
# Kept below 90 so a right angle is always a corner.
_SMOOTH_CORNER_DEGREES = 60.0


def _segments(d: str) -> list[tuple[bool, list[list[float]], list[float]]] | None:
    """Split path data into subpaths of cubic segments. None if unsupported.

    Every segment comes back as ``[c1x, c1y, c2x, c2y, x, y]`` -- a line gets
    control points along its own chord -- so the rest of the code has one
    shape to deal with.
    """
    subpaths: list[tuple[bool, list[list[float]], list[float]]] = []
    current: list[list[float]] = []
    start: list[float] | None = None
    here: list[float] | None = None
    closed = False

    for command, body in _COMMAND_RE.findall(d):
        if command not in _PAIRS_PER_COMMAND:
            return None
        numbers = [float(n) for n in _NUMBER_RE.findall(body)]
        if command == "Z":
            closed = True
            continue
        if len(numbers) % 2:
            return None
        if command == "M":
            if current and start is not None:
                subpaths.append((closed, current, start))
            closed = False
            start = here = numbers[:2]
            current = []
            numbers = numbers[2:]
            command = "L"
        if here is None:
            return None
        step = _PAIRS_PER_COMMAND[command] * 2
        if command == "Q":
            return None  # quadratics are not emitted by the tracer
        for index in range(0, len(numbers), step):
            chunk = numbers[index : index + step]
            if len(chunk) < step:
                return None
            if command == "L":
                end = chunk
                c1 = [here[0] + (end[0] - here[0]) / 3, here[1] + (end[1] - here[1]) / 3]
                c2 = [here[0] + 2 * (end[0] - here[0]) / 3, here[1] + 2 * (end[1] - here[1]) / 3]
                current.append(c1 + c2 + end)
            else:
                current.append(list(chunk))
            here = current[-1][4:6]
    if current and start is not None:
        subpaths.append((closed, current, start))
    return subpaths


def _turn_degrees(before: list[float], node: list[float], after: list[float]) -> float:
    ax, ay = node[0] - before[0], node[1] - before[1]
    bx, by = after[0] - node[0], after[1] - node[1]
    if (ax or ay) and (bx or by):
        cross = ax * by - ay * bx
        dot = ax * bx + ay * by
        return abs(math.degrees(math.atan2(cross, dot)))
    return 0.0


# How much outline either side of a node is looked at when deciding whether it
# is a corner, in source pixels. Long enough to add a split corner back
# together, short enough that a gentle curve does not accumulate into one.
_CORNER_SPAN = 3.0


def _corner_flags(
    segments: list[list[float]], count: int, span: float
) -> list[bool]:
    """Which nodes the curve genuinely turns at, rather than merely wobbling.

    Comparing the two handles at a node is not enough. The tracer often splits
    one corner across two nodes -- a right angle came back as a pair of
    44-degree turns, neither of which looks like a corner on its own, and
    smoothing duly rounded it off. So the direction is measured across a span
    of outline either side instead, which adds a split corner back together
    and averages out a wobble at the same time.
    """
    nodes = [segment[4:6] for segment in segments]

    def reach(index: int, step: int) -> list[float]:
        travelled = 0.0
        cursor = index
        for _ in range(count):
            following = (cursor + step) % count
            travelled += math.dist(nodes[cursor], nodes[following])
            cursor = following
            if travelled >= span:
                break
        return nodes[cursor]

    flags = []
    for index in range(count):
        before, after = reach(index, -1), reach(index, 1)
        flags.append(
            _turn_degrees(before, nodes[index], after) > _SMOOTH_CORNER_DEGREES
        )
    return flags


# How far the simplified curve may stray from the one the tracer produced, in
# source pixels. Every node the tracer emitted marks somewhere the pixel
# boundary turned, so a run of them along one gentle curve is a run of chances
# to wobble; fusing those into a single segment is what finally makes a long
# edge read as one stroke.
#
# The catch is that wobble and fine serration look identical to this test: both
# are a short excursion from the local run of the edge, and the only thing that
# tells them apart is whether the source has one there. At 1.2 it was taking
# the serrations off traced botanical artwork -- the teeth on the coarse fronds
# of the test leaf survived while the fine ones were flattened, which is the
# ragged, part-smoothed edge that gets reported as missing detail.
#
# Swept over the fixtures and the reference samples, the cost is a curve rather
# than a slope, so this is a real optimum and not just "fuse less": mean
# agreement with the source runs 0.3384 / 0.3305 / 0.3324 at 1.2 / 0.6 / 0.3,
# and mean edge agreement 64.78% / 66.24% / 65.12%. Nothing regressed at 0.6 --
# the logo gained most, 65.99% to 71.32% -- and the smooth-edged fixture, which
# has no serration to keep, did not move at all. It costs about 17% in file
# size, which is the wobble that is no longer being fused away on busy artwork.
_SIMPLIFY_TOLERANCE = 0.6

# Points sampled along a pair of segments when measuring how far their
# replacement strays. Enough to catch a bulge in the middle without making the
# check the expensive part of the pass.
_SIMPLIFY_SAMPLES = 8


def _cubic_at(segment: list[float], start: list[float], t: float) -> tuple[float, float]:
    """A point on the cubic that runs from *start* through *segment*."""
    u = 1.0 - t
    a, b, c, d = u * u * u, 3 * u * u * t, 3 * u * t * t, t * t * t
    return (
        a * start[0] + b * segment[0] + c * segment[2] + d * segment[4],
        a * start[1] + b * segment[1] + c * segment[3] + d * segment[5],
    )


def _fuse(
    first: list[float], second: list[float], start: list[float]
) -> list[float] | None:
    """One cubic covering both, or None if the two cannot be spanned.

    The join between them lands at some fraction of the way along the pair, so
    each outer handle is stretched by that fraction to cover the whole span.
    """
    middle = first[4:6]
    span = math.dist(start, middle) + math.dist(middle, second[4:6])
    if not span:
        return None
    share = math.dist(start, middle) / span
    if share <= 0.0 or share >= 1.0:
        return None
    return [
        start[0] + (first[0] - start[0]) / share,
        start[1] + (first[1] - start[1]) / share,
        second[4] + (second[2] - second[4]) / (1.0 - share),
        second[5] + (second[3] - second[5]) / (1.0 - share),
        second[4],
        second[5],
    ]


def _strays(
    fused: list[float],
    first: list[float],
    second: list[float],
    start: list[float],
    tolerance: float,
) -> bool:
    """True if the fused curve wanders further than *tolerance* from the pair."""
    for index in range(1, _SIMPLIFY_SAMPLES):
        t = index / _SIMPLIFY_SAMPLES
        if t < 0.5:
            original = _cubic_at(first, start, t * 2)
        else:
            original = _cubic_at(second, first[4:6], (t - 0.5) * 2)
        if math.dist(original, _cubic_at(fused, start, t)) > tolerance:
            return True
    return False


def _simplify_subpath(
    segments: list[list[float]], corner: list[bool], tolerance: float
) -> tuple[list[list[float]], list[bool]] | None:
    """Fuse neighbouring segments wherever one curve will do for both."""
    count = len(segments)
    if count < 5:
        return None

    keep: list[list[float]] = []
    keep_corner: list[bool] = []
    index = 0
    fused_any = False
    while index < count:
        segment = segments[index]
        following = index + 1
        # The node between the pair is the one that would disappear, so it has
        # to be an ordinary node, and the pair has to stay inside the subpath.
        if following < count and not corner[index]:
            start = segments[index - 1][4:6] if index else segments[-1][4:6]
            fused = _fuse(segment, segments[following], start)
            if fused is not None and not _strays(
                fused, segment, segments[following], start, tolerance
            ):
                keep.append(fused)
                keep_corner.append(corner[following])
                index += 2
                fused_any = True
                continue
        keep.append(list(segment))
        keep_corner.append(corner[index])
        index += 1
    return (keep, keep_corner) if fused_any else None


# A straight run shorter than this, in source pixels, is a chamfer rather than
# an edge the artwork has: the curve fitter reached a bend it would not spend a
# curve on and cut the corner off instead. Six pixels is generous -- the ones
# that show are two to five -- and the test below is what keeps a real short
# edge from being rounded, not this number.
_CHAMFER_MAX_LENGTH = 6.0

# ...and it only counts as a chamfer if its neighbours turn through it. Below
# this the run is part of a straight edge and rounding it would bow the edge;
# above _SMOOTH_CORNER_DEGREES it is a corner the artwork has, and rounding it
# would take the point off a spike.
_CHAMFER_MIN_TURN = 7.0


def _tangent_out(segment: list[float], start: list[float]) -> list[float]:
    """Direction the curve leaves *start* in."""
    for a, b in ((segment[0:2], start), (segment[2:4], start), (segment[4:6], start)):
        dx, dy = a[0] - b[0], a[1] - b[1]
        if math.hypot(dx, dy) > 1e-9:
            return [dx, dy]
    return [0.0, 0.0]


def _tangent_in(segment: list[float], start: list[float]) -> list[float]:
    """Direction the curve arrives at its end in."""
    end = segment[4:6]
    for a in (segment[2:4], segment[0:2], start):
        dx, dy = end[0] - a[0], end[1] - a[1]
        if math.hypot(dx, dy) > 1e-9:
            return [dx, dy]
    return [0.0, 0.0]


def _is_straight(segment: list[float], start: list[float]) -> float | None:
    """Chord length if the segment is a line, None if it curves."""
    dx, dy = segment[4] - start[0], segment[5] - start[1]
    length = math.hypot(dx, dy)
    if length < 1e-9:
        return None
    nx, ny = -dy / length, dx / length
    for handle in (segment[0:2], segment[2:4]):
        offset = abs((handle[0] - start[0]) * nx + (handle[1] - start[1]) * ny)
        if offset >= 0.05:
            return None
    return length


def _round_chamfers(
    segments: list[list[float]], closed: bool, start: list[float], limit: float
) -> int:
    """Turn every corner that was cut flat back into a curve.

    The fitter answers a bend it will not spend a curve on by cutting across
    it, which leaves a short straight run with the turn split between its two
    ends. At a hundred percent that reads as a slightly soft corner; wound in
    to sixty-four times it is a flat facet with a hard kink at each end, and it
    is the thing that stops a traced outline looking drawn.

    The repair keeps the run exactly where it is and only changes how it leaves
    and arrives: its handles are laid along the directions its neighbours
    already have, so the three curves meet tangentially and the facet becomes
    the arc the artwork had. No end point moves, so nothing can drift away from
    the shape, and a run whose neighbours do not turn through it is left alone.
    """
    count = len(segments)
    if count < 3:
        return 0

    heads = [start] + [segment[4:6] for segment in segments[:-1]]
    rounded = 0
    for index in range(count):
        if not closed and (index == 0 or index == count - 1):
            continue
        length = _is_straight(segments[index], heads[index])
        if length is None or length > limit:
            continue

        before = segments[index - 1]
        after = segments[(index + 1) % count]
        incoming = _tangent_in(before, heads[index - 1])
        outgoing = _tangent_out(after, heads[(index + 1) % count])
        first = math.hypot(*incoming)
        second = math.hypot(*outgoing)
        if first < 1e-9 or second < 1e-9:
            continue

        cosine = (incoming[0] * outgoing[0] + incoming[1] * outgoing[1]) / (first * second)
        turn = math.degrees(math.acos(max(-1.0, min(1.0, cosine))))
        if not (_CHAMFER_MIN_TURN < turn < _SMOOTH_CORNER_DEGREES):
            continue

        reach = length / 3.0
        head = heads[index]
        segments[index] = [
            head[0] + incoming[0] / first * reach,
            head[1] + incoming[1] / first * reach,
            segments[index][4] - outgoing[0] / second * reach,
            segments[index][5] - outgoing[1] / second * reach,
            segments[index][4],
            segments[index][5],
        ]
        rounded += 1
    return rounded


def _smooth_subpath(
    segments: list[list[float]],
    closed: bool,
    tolerance: float,
    span: float,
    start: list[float],
    chamfer: float,
) -> list[list[float]]:
    """Fuse neighbouring segments, then round whatever corners were cut flat.

    The two answer different halves of the same fault. Fusing removes nodes
    the tracer spent on a wobble; rounding removes the straight runs it spent
    on a bend. Fusing runs first, because a chamfer between two segments that
    are about to become one should not be rounded into the join.
    """
    count = len(segments)
    if count >= 5 and closed and tolerance:
        segments = _fuse_pass(segments, count, tolerance, span)
    _round_chamfers(segments, closed, start, chamfer)
    return segments


def _fuse_pass(
    segments: list[list[float]], count: int, tolerance: float, span: float
) -> list[list[float]]:
    """Fuse neighbouring segments until one curve will not do for two."""
    corners = _corner_flags(segments, count, span)
    while True:
        fused = _simplify_subpath(segments, corners, tolerance)
        if fused is None:
            break
        segments, corners = fused
    return segments


def _smooth_path_data(
    d: str, tolerance: float, span: float, chamfer: float
) -> str | None:
    """Rewrite path data with fewer, longer segments. None if left alone."""
    subpaths = _segments(d)
    if not subpaths:
        return None
    out = []
    for closed, segments, start in subpaths:
        smoothed = _smooth_subpath(segments, closed, tolerance, span, start, chamfer)
        out.append("M" + " ".join(_fmt(v) for v in start))
        for segment in smoothed:
            out.append("C" + " ".join(_fmt(v) for v in segment))
        if closed:
            out.append("Z")
    return "".join(out)


def _smooth_curves(paths: list[etree._Element], supersample: int = 1) -> int:
    """Take the waviness out of every path that will take it.

    Both measurements are in source pixels, so they scale with whatever
    resolution the bitmap was traced at.
    """
    tolerance = _SIMPLIFY_TOLERANCE * supersample
    span = _CORNER_SPAN * supersample
    chamfer = _CHAMFER_MAX_LENGTH * supersample
    smoothed = 0
    for path in paths:
        data = path.get("d")
        if not data:
            continue
        rewritten = _smooth_path_data(data, tolerance, span, chamfer)
        if rewritten:
            path.set("d", rewritten)
            smoothed += 1
    return smoothed


# --- gradient fills ----------------------------------------------------------
#
# The tracer only ever emits flat fills, so shaded artwork has nowhere to go:
# banding it into narrow strips reads as stripes, and collapsing it to one
# colour throws the shading away. Neither is what the artwork says.
#
# Deciding what a shape was actually shaded with is a job of its own, and one
# that wants real image analysis rather than string handling, so it lives in
# app.services.gradients and is called here as a second stage. It runs at this
# point in the build and not after it because everything below depends on the
# fills being settled: the seam seal is painted from them, and the backdrop is
# chosen by which of them covers the most.


def _apply_gradients(
    root: etree._Element,
    paths: list[etree._Element],
    source: "Image.Image",
    width: int,
    height: int,
    params: VectorizeParams,
    palette: list[str] | None = None,
) -> dict[str, object]:
    """Hand the document to the gradient stage and report what it did."""
    from app.services import gradients

    report = gradients.refine_tree(
        root, paths, source, width, height, params.gradient_params, palette
    )
    return report.as_dict()


def _group_by_color(root: etree._Element, paths: list[etree._Element]) -> None:
    """Collect same-coloured shapes into one <g>, the way designers expect."""
    buckets: OrderedDict[str, list[etree._Element]] = OrderedDict()
    for path in paths:
        key = path.get("fill") or path.get("stroke") or "none"
        buckets.setdefault(key, []).append(path)

    for color, members in buckets.items():
        group = etree.SubElement(root, _q("g"))
        group.set("data-color", color)
        group.set("id", "color-" + color.lstrip("#"))
        for path in members:
            root.remove(path)
            group.append(path)


def _add_seam_backdrop(
    root: etree._Element,
    paths: list[etree._Element],
    params: VectorizeParams,
    w: int,
    h: int,
    source_has_alpha: bool,
) -> None:
    """Lay the dominant ink under everything so a split seam cannot show page.

    The seal stroke in _apply_gap_filler answers anti-aliasing, which is one
    device pixel wide however far you zoom. It cannot answer the other half of
    the problem: the tracer fits every shape's outline on its own, so two
    curves along a shared edge are free to drift apart, and that gap is fixed
    in artwork units — it *grows* on screen as you zoom in, until no stroke of
    constant device width covers it any more. Measured against cached
    Vectorizer.AI output on the reference lettering, whose regions share their
    boundaries exactly and whose leak therefore halves cleanly with every
    doubling of render scale (6735 -> 3370 -> 1689 -> 841 square units), ours
    plateaus at 1139 where anti-aliasing alone predicts 845. That excess is
    real holes, and it is what still showed as black hairlines at high zoom in
    an editor after the seal went in.

    Closing the holes in the geometry would mean making adjacent shapes share
    one fitted curve, which is the tracer's business and not ours. What we can
    do is make sure the answer to "what is behind the artwork" is never the
    page: paint the most-covering ink across the whole canvas first, and a
    split seam reveals that instead of black. Where a gap sits between that
    ink and something else — much the commonest case, since it is the ground
    almost everything borders — the repair is exact.

    Skipped when the source had alpha, where showing through is the point.
    """
    if not params.output_gap_filler_enabled:
        return
    if source_has_alpha:
        return
    if params.output_background:
        return  # an explicit choice already covers the canvas
    if params.output_draw_style != "fill_shapes":
        return

    areas: dict[str, float] = {}
    for path in paths:
        fill = path.get("fill")
        if fill and fill != "none" and not fill.startswith("url("):
            areas[fill] = areas.get(fill, 0.0) + _filled_area(path)
    if not areas:
        return

    rect = etree.Element(_q("rect"))
    rect.set("x", "0")
    rect.set("y", "0")
    rect.set("width", str(w))
    rect.set("height", str(h))
    rect.set("fill", max(areas, key=lambda c: areas[c]))
    root.insert(0, rect)


def _add_background(root: etree._Element, params: VectorizeParams, w: int, h: int) -> None:
    background = params.output_background
    if not background or background == "transparent":
        return
    rect = etree.Element(_q("rect"))
    rect.set("x", "0")
    rect.set("y", "0")
    rect.set("width", str(w))
    rect.set("height", str(h))
    rect.set("fill", background)
    root.insert(0, rect)


def _add_watermark(root: etree._Element, params: VectorizeParams, w: int, h: int) -> None:
    """Mark non-production results so they cannot ship unnoticed."""
    if not params.watermark:
        return

    label = params.mode.upper()
    group = etree.SubElement(root, _q("g"))
    group.set("id", "watermark")
    group.set("opacity", "0.28")
    group.set("pointer-events", "none")

    font_size = max(12.0, min(w, h) / 8.0)
    step_x = font_size * 9.0
    step_y = font_size * 5.0
    rows = int(h / step_y) + 2
    cols = int(w / step_x) + 2

    for row in range(rows):
        for col in range(cols):
            x = col * step_x - (step_x / 2 if row % 2 else 0)
            y = row * step_y
            text = etree.SubElement(group, _q("text"))
            text.set("x", _fmt(x))
            text.set("y", _fmt(y))
            text.set("font-family", "Helvetica, Arial, sans-serif")
            text.set("font-size", _fmt(font_size))
            text.set("font-weight", "bold")
            text.set("fill", "#808080")
            text.set("transform", f"rotate(-30 {_fmt(x)} {_fmt(y)})")
            text.text = label


def _set_geometry(
    root: etree._Element,
    params: VectorizeParams,
    source_w: int,
    source_h: int,
    for_print: bool,
    supersample: int = 1,
) -> tuple[float, float]:
    """Give the document a viewBox and a real-world size.

    The viewBox always stays in tracer pixel space, so scaling is purely a
    presentation concern and never touches the path data. When the bitmap was
    traced at a multiple of its own resolution, that multiple divides out here
    -- the extra pixels bought accuracy, not size.
    """
    root.set("viewBox", f"0 0 {source_w} {source_h}")
    root.set("preserveAspectRatio", "xMidYMid meet")

    target_w, target_h = params.target_size_px(
        source_w / supersample, source_h / supersample
    )

    if for_print:
        # PDF/EPS consumers think in points; emitting points keeps the
        # physical size exact rather than relying on a 96dpi assumption
        # further down the toolchain.
        root.set("width", f"{_fmt(units.px_to_points(target_w))}pt")
        root.set("height", f"{_fmt(units.px_to_points(target_h))}pt")
    elif params.output_size_unit == "px":
        root.set("width", _fmt(target_w))
        root.set("height", _fmt(target_h))
    else:
        unit = params.output_size_unit
        root.set("width", f"{_fmt(units.from_pixels(target_w, unit))}{unit}")
        root.set("height", f"{_fmt(units.from_pixels(target_h, unit))}{unit}")

    return target_w, target_h


def build(
    svg_text: str,
    params: VectorizeParams,
    source_w: int,
    source_h: int,
    *,
    for_print: bool = False,
    palette: list[str] | None = None,
    supersample: int = 1,
    shading: "Image.Image | None" = None,
    source_has_alpha: bool = False,
) -> tuple[bytes, dict[str, object]]:
    """Post-process raw tracer SVG into the final document.

    Returns the serialized SVG and geometry metadata for response headers.
    """
    root = parse(svg_text)

    # Drop the tracer's own generator comment; we add our own below. The
    # comment sits outside the root element, so it has no parent to remove
    # it from and is simply dropped when we re-serialize from `root`.
    for node in root.xpath("//comment()"):
        parent = node.getparent()
        if parent is not None:
            parent.remove(node)

    paths = _paths(root)
    traced_shapes = len(paths)
    if not paths:
        raise VectorizationFailed(
            "No shapes were found. The image may be blank, or "
            "processing.shapes.min_area_px may be filtering everything out."
        )

    # A pinned palette is a promise; honour it before anything else looks at
    # the colours. A palette derived from the artwork gets the same treatment:
    # the pixels were mapped onto it, so the fills have to be too, or the
    # tracer's cluster averages reintroduce the very bands it removed.
    effective_palette = params.processing_palette or palette
    if effective_palette:
        _snap_to_palette(paths, effective_palette)
    merged = _merge_similar_colors(paths, params.processing_color_merge)
    _smooth_curves(paths, supersample)
    # Flat fills that cover a ramp become gradients.
    #
    # A palette the *caller* chose is a promise, and a gradient would break it:
    # asking for six inks and getting a ramp is not what was ordered, so the
    # fills stay flat there. A palette the detector derived is not a promise,
    # it is a guess that the artwork is flat -- and where the guess is wrong it
    # is wrong in exactly the way that shows: a ramp gets cut into two inks,
    # and every shape it crosses comes back as hard-edged patches of the two
    # with a ragged step between them. So the guess is checked rather than
    # trusted, against the artwork's own pixels from before they were mapped
    # onto the palette, which is the only copy that still has the ramp in it.
    shading_report: dict[str, object] = {}
    if shading is not None and (not effective_palette or params.auto_palette):
        shading_report = _apply_gradients(
            root, paths, shading, source_w, source_h, params, effective_palette
        )
    _apply_draw_style(paths, params)
    _apply_gap_filler(
        paths, params, _canvas_is_covered(params, source_has_alpha)
    )
    _add_seam_backdrop(root, paths, params, source_w, source_h, source_has_alpha)
    _add_background(root, params, source_w, source_h)
    combined = "none"
    if params.output_combine_paths != "none":
        _combine_by_color(root, paths, params.output_combine_paths)
        paths = _paths(root)
        combined = params.output_combine_paths
    if params.output_group_by == "color":
        _group_by_color(root, paths)
    target_w, target_h = _set_geometry(
        root, params, source_w, source_h, for_print, supersample
    )
    _add_watermark(root, params, source_w, source_h)

    root.set("version", "1.1")

    # Serialize the element rather than the tree: the tracer's generator
    # comment is a sibling of the root at document level, which lxml cannot
    # detach, so writing from `root` is what actually drops it.
    body = _PROLOGUE + etree.tostring(
        root,
        xml_declaration=False,
        encoding="UTF-8",
        pretty_print=True,
    )

    meta: dict[str, object] = {
        "paths": len(_paths(root)),
        "shapes": traced_shapes,
        "combined": combined,
        "gradients": shading_report.get("gradients", 0),
        "shading": shading_report,
        "source_width": source_w,
        "source_height": source_h,
        "output_width": target_w,
        "output_height": target_h,
    }
    return body, meta


def count_colors(svg_text: str) -> int:
    root = parse(svg_text)
    return len({p.get("fill") for p in _paths(root) if p.get("fill")})
