"""SVG post-processing.

The tracer emits a bare list of filled paths. Everything that turns that
into a usable, editable document happens here: a proper coordinate system,
physical output size, draw styles, colour grouping, seam removal and
watermarking.
"""

from __future__ import annotations

import re
from collections import OrderedDict

from lxml import etree

from app.core.errors import VectorizationFailed
from app.schemas.params import VectorizeParams
from app.utils import units

SVG_NS = "http://www.w3.org/2000/svg"
NSMAP = {None: SVG_NS}

_NUMBER_RE = re.compile(r"-?\d+\.?\d*")

_PROLOGUE = (
    b'<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
    b"<!-- Generated by Python Vector API -->\n"
)


def _q(tag: str) -> str:
    return f"{{{SVG_NS}}}{tag}"


def _fmt(value: float) -> str:
    """Compact number formatting: 300.0 -> '300', 12.3456 -> '12.346'."""
    rounded = round(value, 3)
    if rounded == int(rounded):
        return str(int(rounded))
    return f"{rounded:g}"


def parse(svg_text: str) -> etree._Element:
    parser = etree.XMLParser(remove_blank_text=False, resolve_entities=False, huge_tree=False)
    try:
        return etree.fromstring(svg_text.encode("utf-8"), parser=parser)
    except etree.XMLSyntaxError as exc:  # pragma: no cover - tracer emits valid XML
        raise VectorizationFailed(f"The tracer produced invalid SVG: {exc}") from exc


def _paths(root: etree._Element) -> list[etree._Element]:
    return list(root.iter(_q("path")))


def _apply_draw_style(paths: list[etree._Element], params: VectorizeParams) -> None:
    """Re-express each shape as fill, outline, or bare edge."""
    style = params.output_draw_style
    if style == "fill_shapes":
        return

    width = _fmt(params.output_stroke_width)
    for path in paths:
        fill = path.get("fill", "#000000")
        path.set("fill", "none")
        path.set("stroke", "#000000" if style == "stroke_edges" else fill)
        path.set("stroke-width", width)
        path.set("stroke-linejoin", "round")
        path.set("stroke-linecap", "round")


def _apply_gap_filler(paths: list[etree._Element], params: VectorizeParams) -> None:
    """Hide the hairline seams renderers leave between abutting shapes.

    Adjacent traced shapes share an edge exactly. Anti-aliasing each of them
    independently leaves a faint light line along that shared edge, so we
    stroke every shape with its own fill colour to overlap the seam.
    """
    if not params.output_gap_filler_enabled:
        return
    if params.output_draw_style != "fill_shapes":
        return  # stroked output has no seams to hide

    width = _fmt(params.output_gap_filler_stroke_width)
    for path in paths:
        fill = path.get("fill")
        if not fill or fill == "none":
            continue
        path.set("stroke", fill)
        path.set("stroke-width", width)
        path.set("stroke-linejoin", "round")


def _rgb(value: str) -> tuple[int, int, int] | None:
    value = value.strip()
    if not value.startswith("#") or len(value) not in (4, 7):
        return None
    if len(value) == 4:
        value = "#" + "".join(ch * 2 for ch in value[1:])
    try:
        return tuple(int(value[i : i + 2], 16) for i in (1, 3, 5))  # type: ignore[return-value]
    except ValueError:
        return None


def _filled_area(path: etree._Element) -> float:
    """Approximate enclosed area, used to rank colours by prominence.

    Shoelace over the path's control points. It is only an approximation for
    curves, but the important property is that it measures what a shape
    *covers* -- a bounding box does not, and a thin ring's box is as big as
    the shape it surrounds, which would rank a transition band above the fill
    it borders and merge colours in exactly the wrong direction.
    """
    numbers = [float(n) for n in _NUMBER_RE.findall(path.get("d") or "")]
    xs, ys = numbers[0::2], numbers[1::2]
    count = min(len(xs), len(ys))
    if count < 3:
        return 0.0
    total = 0.0
    for i in range(count):
        j = (i + 1) % count
        total += xs[i] * ys[j] - xs[j] * ys[i]
    return abs(total) / 2.0


def _resolve_blend(
    colour: tuple[int, int, int], targets: list[tuple[str, tuple[int, int, int]]]
) -> str:
    """Decide which palette colour a traced fill really belongs to.

    The tracer averages the pixels inside each cluster, so a cluster straddling
    a boundary comes back as a blend of the two colours either side. Snapping
    such a blend to the *nearest* palette entry is wrong, and wrong in a way
    that is very visible: the midpoint of a dark charcoal and a cream sits
    close to a sage green, so every letter grew a green outline that exists
    nowhere in the artwork.

    Instead, find the pair of palette colours whose mixture best explains the
    blend, and award it to whichever of the two dominates. A dark/cream blend
    resolves to dark or cream -- never to some third colour that merely
    happens to sit nearby in RGB space.
    """
    best_error = float("inf")
    best_name = targets[0][0]
    for i, (name_a, a) in enumerate(targets):
        for name_b, b in targets[i:]:
            delta = tuple(bc - ac for ac, bc in zip(a, b))
            length = sum(d * d for d in delta)
            if length == 0:
                weight = 0.0
            else:
                # Project the blend onto the a->b line, clamped to the segment.
                weight = sum(
                    (c - ac) * d for c, ac, d in zip(colour, a, delta)
                ) / length
                weight = max(0.0, min(1.0, weight))
            mixed = tuple(ac + weight * d for ac, d in zip(a, delta))
            error = sum((c - m) ** 2 for c, m in zip(colour, mixed))
            if error < best_error:
                best_error = error
                best_name = name_b if weight > 0.5 else name_a
    return best_name


def _snap_to_palette(paths: list[etree._Element], palette: list[str]) -> int:
    """Force every fill onto the requested palette.

    The bitmap handed to the tracer already contains exactly these colours,
    but the tracer averages within clusters, so ask for six colours and two
    hundred come out. The extras show up in an editor as ghost layers beside
    the real shapes, so they have to be resolved back to the palette.
    """
    targets = [(colour, _rgb(colour)) for colour in palette]
    targets = [(colour, rgb) for colour, rgb in targets if rgb is not None]
    if not targets:
        return 0

    snapped = 0
    cache: dict[str, str] = {}
    for path in paths:
        fill = path.get("fill")
        if not fill or fill == "none":
            continue
        if fill not in cache:
            source = _rgb(fill)
            if source is None:
                continue
            cache[fill] = _resolve_blend(source, targets)
        nearest = cache[fill]
        if nearest != fill:
            snapped += 1
        path.set("fill", nearest)
        if path.get("stroke") and path.get("stroke") != "none":
            path.set("stroke", nearest)  # gap filler tracks the fill
    return snapped


def _merge_similar_colors(paths: list[etree._Element], threshold: float) -> int:
    """Snap near-duplicate fills onto the dominant colour they sit beside.

    Anti-aliasing between two flat regions leaves a transition band, and the
    tracer emits it as its own shapes -- pale lumps sitting between a dark
    stroke and its fill. Worse, it often splits that band into fills a single
    RGB unit apart (#4d3e48 next to #4d3f48). No tracer setting merges those,
    because to the tracer they really are different colours.

    So collapse them afterwards: rank fills by how much area they cover, then
    remap each minor colour onto the nearest more-prominent one within
    *threshold* RGB distance.
    """
    if threshold <= 0:
        return 0

    area_by_color: dict[str, float] = {}
    for path in paths:
        fill = path.get("fill")
        if fill and fill != "none":
            area_by_color[fill] = area_by_color.get(fill, 0.0) + _filled_area(path)

    # Most prominent first, so minor colours dissolve into major ones and
    # never the other way round.
    ranked = sorted(area_by_color, key=lambda c: area_by_color[c], reverse=True)
    remap: dict[str, str] = {}
    for index, color in enumerate(ranked):
        source = _rgb(color)
        if source is None:
            continue
        best, best_distance = None, threshold
        for major in ranked[:index]:
            target = _rgb(remap.get(major, major))
            if target is None:
                continue
            distance = sum((a - b) ** 2 for a, b in zip(source, target)) ** 0.5
            if distance <= best_distance:
                best, best_distance = remap.get(major, major), distance
        if best is not None:
            remap[color] = best

    if not remap:
        return 0
    for path in paths:
        fill = path.get("fill")
        if fill in remap:
            path.set("fill", remap[fill])
            if path.get("stroke") == fill:  # gap filler tracks the fill
                path.set("stroke", remap[fill])
    return len(remap)


_COMMAND_RE = re.compile(r"([MLCQZmlcqz])([^MLCQZmlcqz]*)")

# Coordinate pairs consumed by each absolute path command.
_PAIRS_PER_COMMAND = {"M": 1, "L": 1, "C": 3, "Q": 2, "Z": 0}


def _shift_path_data(d: str, dx: float, dy: float) -> str | None:
    """Bake a translate into absolute path data. None if it is not safe to.

    The tracer emits a per-shape ``transform="translate(x,y)"``. Combining
    shapes into one element means their coordinates have to live in the same
    space, so the offset is folded into the numbers here.
    """
    out: list[str] = []
    for command, body in _COMMAND_RE.findall(d):
        if command not in _PAIRS_PER_COMMAND:
            return None  # relative command: leave this path alone
        if command == "Z":
            out.append("Z")
            continue
        numbers = [float(n) for n in _NUMBER_RE.findall(body)]
        if len(numbers) % 2:
            return None
        shifted = []
        for i in range(0, len(numbers), 2):
            shifted.append(_fmt(numbers[i] + dx))
            shifted.append(_fmt(numbers[i + 1] + dy))
        out.append(command + " ".join(shifted))
    return "".join(out)


_TRANSLATE_RE = re.compile(
    r"translate\(\s*(-?\d+\.?\d*)[ ,]+(-?\d+\.?\d*)\s*\)"
)


def _path_bounds(path: etree._Element) -> tuple[float, float, float, float] | None:
    """Bounding box in document space, with the shape's translate applied."""
    numbers = [float(n) for n in _NUMBER_RE.findall(path.get("d") or "")]
    xs, ys = numbers[0::2], numbers[1::2]
    if not xs or not ys:
        return None
    match = _TRANSLATE_RE.search(path.get("transform") or "")
    dx, dy = (float(match.group(1)), float(match.group(2))) if match else (0.0, 0.0)
    return (min(xs) + dx, min(ys) + dy, max(xs) + dx, max(ys) + dy)


def _touching_groups(
    paths: list[etree._Element], tolerance: float = 1.0
) -> list[list[etree._Element]]:
    """Cluster same-colour shapes that touch, so each letter stays its own object.

    The tracer breaks a single letter into several fragments, but merging a
    whole colour into one path goes too far the other way: a word becomes one
    object you cannot pick letters out of. Grouping by overlapping bounds
    keeps separate glyphs separate while still fusing the pieces of each.

    Bounds overlap is a deliberate approximation -- two tightly kerned letters
    whose boxes intersect will merge. That is far less disruptive than either
    extreme.
    """
    boxes = [(path, _path_bounds(path)) for path in paths]
    usable = [(path, box) for path, box in boxes if box is not None]

    parent = list(range(len(usable)))

    def find(i: int) -> int:
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    def union(a: int, b: int) -> None:
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[rb] = ra

    for i in range(len(usable)):
        ax0, ay0, ax1, ay1 = usable[i][1]
        for j in range(i + 1, len(usable)):
            bx0, by0, bx1, by1 = usable[j][1]
            if (
                ax0 - tolerance <= bx1
                and bx0 - tolerance <= ax1
                and ay0 - tolerance <= by1
                and by0 - tolerance <= ay1
            ):
                union(i, j)

    clusters: OrderedDict[int, list[etree._Element]] = OrderedDict()
    for index, (path, _) in enumerate(usable):
        clusters.setdefault(find(index), []).append(path)
    groups = list(clusters.values())
    groups.extend([path] for path, box in boxes if box is None)
    return groups


def _combine_by_color(
    root: etree._Element, paths: list[etree._Element], mode: str
) -> int:
    """Fuse all shapes sharing a fill into one path element.

    The tracer emits every shape separately, so a six-colour illustration can
    arrive in an editor as hundreds of objects -- one real case opened in
    CorelDRAW as "Group of 761 Objects", which is unusable for selecting or
    recolouring. Subpaths of one path render identically but count as a single
    object, so this collapses the file to roughly one object per colour.
    """
    by_fill: OrderedDict[str, list[etree._Element]] = OrderedDict()
    for path in paths:
        fill = path.get("fill")
        if not fill or fill == "none":
            continue
        by_fill.setdefault(fill, []).append(path)

    if mode == "colors":
        groups = list(by_fill.values())
    else:
        groups = [g for members in by_fill.values() for g in _touching_groups(members)]

    combined = 0
    for members in groups:
        if len(members) < 2:
            continue
        pieces: list[str] = []
        for path in members:
            data = path.get("d") or ""
            transform = path.get("transform") or ""
            match = _TRANSLATE_RE.search(transform)
            dx, dy = (float(match.group(1)), float(match.group(2))) if match else (0.0, 0.0)
            if transform and not match:
                pieces = []  # unexpected transform; do not risk moving artwork
                break
            shifted = _shift_path_data(data, dx, dy)
            if shifted is None:
                pieces = []
                break
            pieces.append(shifted)
        if not pieces:
            continue

        keeper = members[0]
        keeper.set("d", "".join(pieces))
        keeper.attrib.pop("transform", None)
        # Subpaths traced independently have no consistent winding direction,
        # so the default nonzero rule would fill counters and holes solid.
        keeper.set("fill-rule", "evenodd")
        for extra in members[1:]:
            parent = extra.getparent()
            if parent is not None:
                parent.remove(extra)
        combined += len(members) - 1
    return combined


def _group_by_color(root: etree._Element, paths: list[etree._Element]) -> None:
    """Collect same-coloured shapes into one <g>, the way designers expect."""
    buckets: OrderedDict[str, list[etree._Element]] = OrderedDict()
    for path in paths:
        key = path.get("fill") or path.get("stroke") or "none"
        buckets.setdefault(key, []).append(path)

    for color, members in buckets.items():
        group = etree.SubElement(root, _q("g"))
        group.set("data-color", color)
        group.set("id", "color-" + color.lstrip("#"))
        for path in members:
            root.remove(path)
            group.append(path)


def _add_background(root: etree._Element, params: VectorizeParams, w: int, h: int) -> None:
    background = params.output_background
    if not background or background == "transparent":
        return
    rect = etree.Element(_q("rect"))
    rect.set("x", "0")
    rect.set("y", "0")
    rect.set("width", str(w))
    rect.set("height", str(h))
    rect.set("fill", background)
    root.insert(0, rect)


def _add_watermark(root: etree._Element, params: VectorizeParams, w: int, h: int) -> None:
    """Mark non-production results so they cannot ship unnoticed."""
    if not params.watermark:
        return

    label = params.mode.upper()
    group = etree.SubElement(root, _q("g"))
    group.set("id", "watermark")
    group.set("opacity", "0.28")
    group.set("pointer-events", "none")

    font_size = max(12.0, min(w, h) / 8.0)
    step_x = font_size * 9.0
    step_y = font_size * 5.0
    rows = int(h / step_y) + 2
    cols = int(w / step_x) + 2

    for row in range(rows):
        for col in range(cols):
            x = col * step_x - (step_x / 2 if row % 2 else 0)
            y = row * step_y
            text = etree.SubElement(group, _q("text"))
            text.set("x", _fmt(x))
            text.set("y", _fmt(y))
            text.set("font-family", "Helvetica, Arial, sans-serif")
            text.set("font-size", _fmt(font_size))
            text.set("font-weight", "bold")
            text.set("fill", "#808080")
            text.set("transform", f"rotate(-30 {_fmt(x)} {_fmt(y)})")
            text.text = label


def _set_geometry(
    root: etree._Element,
    params: VectorizeParams,
    source_w: int,
    source_h: int,
    for_print: bool,
    supersample: int = 1,
) -> tuple[float, float]:
    """Give the document a viewBox and a real-world size.

    The viewBox always stays in tracer pixel space, so scaling is purely a
    presentation concern and never touches the path data. When the bitmap was
    traced at a multiple of its own resolution, that multiple divides out here
    -- the extra pixels bought accuracy, not size.
    """
    root.set("viewBox", f"0 0 {source_w} {source_h}")
    root.set("preserveAspectRatio", "xMidYMid meet")

    target_w, target_h = params.target_size_px(
        source_w / supersample, source_h / supersample
    )

    if for_print:
        # PDF/EPS consumers think in points; emitting points keeps the
        # physical size exact rather than relying on a 96dpi assumption
        # further down the toolchain.
        root.set("width", f"{_fmt(units.px_to_points(target_w))}pt")
        root.set("height", f"{_fmt(units.px_to_points(target_h))}pt")
    elif params.output_size_unit == "px":
        root.set("width", _fmt(target_w))
        root.set("height", _fmt(target_h))
    else:
        unit = params.output_size_unit
        root.set("width", f"{_fmt(units.from_pixels(target_w, unit))}{unit}")
        root.set("height", f"{_fmt(units.from_pixels(target_h, unit))}{unit}")

    return target_w, target_h


def build(
    svg_text: str,
    params: VectorizeParams,
    source_w: int,
    source_h: int,
    *,
    for_print: bool = False,
    palette: list[str] | None = None,
    supersample: int = 1,
) -> tuple[bytes, dict[str, float | int]]:
    """Post-process raw tracer SVG into the final document.

    Returns the serialized SVG and geometry metadata for response headers.
    """
    root = parse(svg_text)

    # Drop the tracer's own generator comment; we add our own below. The
    # comment sits outside the root element, so it has no parent to remove
    # it from and is simply dropped when we re-serialize from `root`.
    for node in root.xpath("//comment()"):
        parent = node.getparent()
        if parent is not None:
            parent.remove(node)

    paths = _paths(root)
    traced_shapes = len(paths)
    if not paths:
        raise VectorizationFailed(
            "No shapes were found. The image may be blank, or "
            "processing.shapes.min_area_px may be filtering everything out."
        )

    # A pinned palette is a promise; honour it before anything else looks at
    # the colours. A palette derived from the artwork gets the same treatment:
    # the pixels were mapped onto it, so the fills have to be too, or the
    # tracer's cluster averages reintroduce the very bands it removed.
    effective_palette = params.processing_palette or palette
    if effective_palette:
        _snap_to_palette(paths, effective_palette)
    merged = _merge_similar_colors(paths, params.processing_color_merge)
    _apply_draw_style(paths, params)
    _apply_gap_filler(paths, params)
    _add_background(root, params, source_w, source_h)
    combined = "none"
    if params.output_combine_paths != "none":
        _combine_by_color(root, paths, params.output_combine_paths)
        paths = _paths(root)
        combined = params.output_combine_paths
    if params.output_group_by == "color":
        _group_by_color(root, paths)
    target_w, target_h = _set_geometry(
        root, params, source_w, source_h, for_print, supersample
    )
    _add_watermark(root, params, source_w, source_h)

    root.set("version", "1.1")

    # Serialize the element rather than the tree: the tracer's generator
    # comment is a sibling of the root at document level, which lxml cannot
    # detach, so writing from `root` is what actually drops it.
    body = _PROLOGUE + etree.tostring(
        root,
        xml_declaration=False,
        encoding="UTF-8",
        pretty_print=True,
    )

    meta: dict[str, float | int] = {
        "paths": len(_paths(root)),
        "shapes": traced_shapes,
        "combined": combined,
        "source_width": source_w,
        "source_height": source_h,
        "output_width": target_w,
        "output_height": target_h,
    }
    return body, meta


def count_colors(svg_text: str) -> int:
    root = parse(svg_text)
    return len({p.get("fill") for p in _paths(root) if p.get("fill")})
